import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { ArrowUpRight, Bath, BedDouble, Bell, Building2, ChevronDown, Heart, Home, LogOut, MapPin, Menu, Pencil, Plus, Search, ShieldCheck, SlidersHorizontal, Sparkles, Trash2, Users, X } from 'lucide-react'
import './styles.css'

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000/api'
const DEMO = [
  { id: 1, title: 'The Willow House', location: 'Indiranagar, Bengaluru', type: 'Villa', rooms: 4, price: 28500000, image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=85', featured: true, match: 96 },
  { id: 2, title: 'Lakeside Loft', location: 'Koregaon Park, Pune', type: 'Apartment', rooms: 3, price: 12800000, image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=85', match: 91 },
  { id: 3, title: 'Cedar Court', location: 'Whitefield, Bengaluru', type: 'Apartment', rooms: 2, price: 7600000, image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=85', match: 88 },
  { id: 4, title: 'Palm Grove Estate', location: 'ECR, Chennai', type: 'Villa', rooms: 5, price: 41200000, image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=85', match: 84 },
  { id: 5, title: 'Moss & Marble', location: 'Hitech City, Hyderabad', type: 'Apartment', rooms: 3, price: 9400000, image: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1000&q=85', match: 82 },
  { id: 6, title: 'The Courtyard', location: 'Alwarpet, Chennai', type: 'House', rooms: 4, price: 21900000, image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1000&q=85', match: 79 }
]
const formatPrice = n => n >= 10000000 ? `₹${(n / 10000000).toFixed(2)} Cr` : `₹${(n / 100000).toFixed(0)} L`
const getUser = () => JSON.parse(localStorage.getItem('propconnect_user') || 'null')

async function request(path, options = {}) {
  const token = localStorage.getItem('propconnect_token')
  try {
    const res = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } })
    if (!res.ok) throw new Error('Request failed')
    return await res.json()
  } catch { return null }
}

function App() {
  const [user, setUser] = useState(getUser())
  const logout = () => { localStorage.clear(); setUser(null) }
  return <BrowserRouter><Routes>
    <Route path="/login" element={<Auth mode="login" onAuth={setUser} />} />
    <Route path="/register" element={<Auth mode="register" onAuth={setUser} />} />
    <Route path="*" element={user ? <Shell user={user} logout={logout} /> : <Navigate to="/login" replace />} />
  </Routes></BrowserRouter>
}

function Auth({ mode, onAuth }) {
  const navigate = useNavigate(); const [form, setForm] = useState({ name: '', email: '', password: '', role: 'buyer' }); const [error, setError] = useState('')
  const submit = async e => { e.preventDefault(); setError(''); const result = await request(`/auth/${mode === 'login' ? 'login' : 'register'}`, { method: 'POST', body: JSON.stringify(form) }); const account = result || { access_token: 'demo', user: { id: 1, name: form.name || 'Aarav Mehta', email: form.email, role: form.role } }; localStorage.setItem('propconnect_token', account.access_token); localStorage.setItem('propconnect_user', JSON.stringify(account.user)); onAuth(account.user); navigate('/dashboard') }
  return <main className="auth-page"><div className="auth-visual"><div className="brand inverse"><span className="brand-mark"><Building2 size={18}/></span> propconnect</div><div className="visual-copy"><p className="eyebrow">A better place to begin</p><h1>Find a place that feels like <em>yours.</em></h1><p>Thoughtful homes. Clear decisions. A marketplace built around how you actually want to live.</p></div><div className="visual-meta"><span>01</span><div className="progress"><i/></div><span>03</span></div></div><div className="auth-panel"><div className="mobile-brand brand"><span className="brand-mark"><Building2 size={18}/></span> propconnect</div><div className="auth-heading"><span className="eyebrow">{mode === 'login' ? 'Welcome back' : 'Start your search'}</span><h2>{mode === 'login' ? 'Sign in to your space' : 'Create your account'}</h2><p>{mode === 'login' ? 'Your next chapter is closer than you think.' : 'Join a calmer, smarter way to find a home.'}</p></div><form onSubmit={submit}>{mode === 'register' && <label>Full name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Aarav Mehta" /></label>}<label>Email address<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" /></label><label>Password<input required type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} placeholder="••••••••" /></label>{mode === 'register' && <label>I'm here to <select value={form.role} onChange={e => setForm({ ...form, role: e.target.value })}><option value="buyer">Find a property</option><option value="seller">List a property</option></select></label>}{error && <p className="error">{error}</p>}<button className="primary full">{mode === 'login' ? 'Sign in' : 'Create account'} <ArrowUpRight size={17}/></button></form><p className="switch-auth">{mode === 'login' ? "Don't have an account?" : 'Already have an account?'} <Link to={mode === 'login' ? '/register' : '/login'}>{mode === 'login' ? 'Create one' : 'Sign in'}</Link></p><p className="demo-note">Demo mode is ready: any valid form details will open the app.</p></div></main>
}

function Shell({ user, logout }) {
  const location = useLocation(); const [open, setOpen] = useState(false); const buyer = user.role === 'buyer'
  const nav = buyer ? [{ to: '/dashboard', label: 'Overview', icon: Home }, { to: '/properties', label: 'Explore homes', icon: Search }, { to: '/favourites', label: 'Favourites', icon: Heart }, { to: '/interests', label: 'My requests', icon: Bell }] : [{ to: '/dashboard', label: 'Overview', icon: Home }, { to: '/my-listings', label: 'My listings', icon: Building2 }, { to: '/add-property', label: 'Add property', icon: Plus }, { to: '/interests', label: 'Interest requests', icon: Users }]
  return <div className="app-shell"><aside className={open ? 'sidebar open' : 'sidebar'}><div className="brand"><span className="brand-mark"><Building2 size={18}/></span> propconnect</div><div className="workspace"><span className="avatar">{(user.name || 'A').charAt(0)}</span><div><strong>{user.name || 'Aarav Mehta'}</strong><small>{buyer ? 'Buyer account' : 'Seller account'}</small></div><ChevronDown size={15}/></div><nav>{nav.map(({ to, label, icon: Icon }) => <Link key={to} onClick={() => setOpen(false)} className={location.pathname === to ? 'active' : ''} to={to}><Icon size={18}/><span>{label}</span></Link>)}</nav><div className="sidebar-bottom"><div className="trust"><ShieldCheck size={18}/><div><strong>Verified marketplace</strong><small>Secure by design</small></div></div><button className="logout" onClick={logout}><LogOut size={17}/> Sign out</button></div></aside><div className="main"><header><button className="menu-button" onClick={() => setOpen(!open)}><Menu size={20}/></button><div className="crumb">{buyer ? 'Buyer workspace' : 'Seller workspace'} <span>/</span> <strong>{nav.find(n => n.to === location.pathname)?.label || 'Overview'}</strong></div><div className="header-actions"><button className="icon-button"><Bell size={19}/><i/></button><div className="header-avatar">{(user.name || 'A').charAt(0)}</div></div></header><div className="content"><Routes><Route path="/dashboard" element={buyer ? <BuyerDashboard user={user}/> : <SellerDashboard/>}/><Route path="/properties" element={<Explore/>}/><Route path="/property/:id" element={<PropertyDetails/>}/><Route path="/favourites" element={<Favourites/>}/><Route path="/interests" element={<Interests seller={!buyer}/>}/><Route path="/my-listings" element={<SellerDashboard/>}/><Route path="/add-property" element={<PropertyForm/>}/><Route path="/edit-property/:id" element={<PropertyForm edit/>}/><Route path="*" element={<Navigate to="/dashboard" replace/>}/></Routes></div></div></div>
}

function PageTitle({ eyebrow, title, copy, action }) { return <div className="page-title"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{copy && <p className="subcopy">{copy}</p>}</div>{action}</div> }
function Stat({ label, value, note, icon: Icon }) { return <div className="stat"><div className="stat-top"><span>{label}</span><Icon size={18}/></div><strong>{value}</strong><small>{note}</small></div> }
function PropertyCard({ property, compact = false }) { const [liked, setLiked] = useState(false); return <article className={compact ? 'property-card compact' : 'property-card'}><Link to={`/property/${property.id}`} className="property-image"><img src={property.image} /><span className="type-pill">{property.type}</span>{property.match && <span className="match-pill"><Sparkles size={12}/> {property.match}% match</span>}<button className={liked ? 'heart active' : 'heart'} onClick={e => { e.preventDefault(); setLiked(!liked); request(`/properties/${property.id}/favorite`, { method: 'POST' }) }}><Heart size={17} fill={liked ? 'currentColor' : 'none'}/></button></Link><div className="property-body"><div className="property-heading"><div><h3>{property.title}</h3><p><MapPin size={14}/> {property.location}</p></div><strong>{formatPrice(property.price)}</strong></div><div className="property-meta"><span><BedDouble size={15}/> {property.rooms} beds</span><span><Bath size={15}/> {property.rooms + 1} baths</span><span>{property.type}</span></div></div></article> }
function BuyerDashboard() { const [query, setQuery] = useState(''); const list = DEMO.filter(p => p.location.toLowerCase().includes(query.toLowerCase())); return <><PageTitle eyebrow="Tuesday, 10 September 2026" title="Good morning, Aarav" copy="Here’s a little inspiration for your next move." action={<Link className="primary" to="/properties">Explore homes <ArrowUpRight size={17}/></Link>}/><section className="hero-banner"><div><span className="eyebrow">Curated for you</span><h2>Make room for<br/><em>what matters.</em></h2><p>Homes matched to your taste, budget, and the places you love.</p><Link to="/properties" className="text-link">Discover your match <ArrowUpRight size={16}/></Link></div><div className="hero-stat"><Sparkles size={18}/><strong>12</strong><span>fresh matches<br/>this week</span></div></section><div className="section-heading"><div><h2>Recommended for you</h2><p>Based on your recent searches and saved homes</p></div><Link to="/properties" className="text-link">View all <ArrowUpRight size={16}/></Link></div><div className="property-grid">{list.slice(0, 3).map(p => <PropertyCard key={p.id} property={p}/>)}</div><div className="dashboard-lower"><div className="activity-panel"><div className="section-heading"><div><h2>Your activity</h2><p>Keep track of your property journey</p></div><SlidersHorizontal size={18}/></div><div className="activity-row"><span className="activity-icon saved"><Heart size={17}/></span><div><strong>3 homes saved</strong><small>Last saved in Whitefield</small></div><b>2 days ago</b></div><div className="activity-row"><span className="activity-icon searched"><Search size={17}/></span><div><strong>Search in Indiranagar</strong><small>2–4 bedrooms · ₹1–3 Cr</small></div><b>5 days ago</b></div></div><div className="insight-panel"><Sparkles size={20}/><span className="eyebrow">Your property pulse</span><h3>You're drawn to<br/><em>light-filled spaces.</em></h3><p>Most of your saved homes have large windows and a quiet neighbourhood.</p></div></div></> }
function Explore() { const [q, setQ] = useState(''); const [type, setType] = useState('All types'); const [sort, setSort] = useState('Recommended'); const filtered = DEMO.filter(p => p.location.toLowerCase().includes(q.toLowerCase()) && (type === 'All types' || p.type === type)).sort((a,b) => sort === 'Price: low to high' ? a.price - b.price : sort === 'Price: high to low' ? b.price - a.price : b.match - a.match); return <><PageTitle eyebrow="Explore" title="Find your next address" copy="Browse considered spaces from verified sellers."/><div className="filters"><div className="search-field"><Search size={18}/><input value={q} onChange={e => setQ(e.target.value)} placeholder="Search by location"/></div><select value={type} onChange={e => setType(e.target.value)}><option>All types</option><option>Apartment</option><option>Villa</option><option>House</option></select><select value={sort} onChange={e => setSort(e.target.value)}><option>Recommended</option><option>Price: low to high</option><option>Price: high to low</option></select><button className="filter-button"><SlidersHorizontal size={17}/> Filters</button></div><div className="results-line"><span><strong>{filtered.length}</strong> homes that might be right for you</span><span className="live"><i/> Live listings</span></div><div className="property-grid wide">{filtered.map(p => <PropertyCard key={p.id} property={p}/>)}</div></> }
function PropertyDetails() { const { id } = useParams(); const p = DEMO.find(x => String(x.id) === id) || DEMO[0]; const [sent, setSent] = useState(false); return <><Link to="/properties" className="back-link">← Back to explore</Link><div className="detail-layout"><div><img className="detail-image" src={p.image}/><div className="thumb-row"><img src={p.image}/><img src={DEMO[1].image}/><img src={DEMO[2].image}/></div></div><div className="detail-copy"><span className="eyebrow">{p.type} · Verified listing</span><h1>{p.title}</h1><p className="detail-location"><MapPin size={17}/> {p.location}</p><div className="detail-price"><strong>{formatPrice(p.price)}</strong><span>Ready to move in</span></div><div className="detail-features"><span><BedDouble/><strong>{p.rooms}</strong> Bedrooms</span><span><Bath/><strong>{p.rooms + 1}</strong> Bathrooms</span><span><Home/><strong>1,980</strong> sq.ft.</span></div><p className="detail-description">A warm, considered home designed for slow mornings and easy evenings. Natural light, generous proportions, and the kind of neighbourhood that gives you room to breathe.</p><div className="seller-card"><span className="avatar large">RK</span><div><strong>Rhea Kapoor</strong><small>Verified property partner</small></div><button className="icon-button"><ArrowUpRight size={17}/></button></div><button className="primary full" onClick={() => { setSent(true); request(`/properties/${p.id}/interest`, { method: 'POST' }) }}>{sent ? 'Interest sent ✓' : "I'm interested"} <ArrowUpRight size={17}/></button></div></div></> }
function Favourites() { return <><PageTitle eyebrow="Your collection" title="Saved homes" copy="The places you keep coming back to."/><div className="property-grid wide">{DEMO.slice(0, 4).map(p => <PropertyCard key={p.id} property={p}/>)}</div></> }
function Interests({ seller }) { const requests = [{ name: 'Aarav Mehta', property: 'The Willow House', date: 'Today, 10:42 AM', status: 'New', avatar: 'AM' }, { name: 'Nisha Shah', property: 'Lakeside Loft', date: 'Yesterday, 4:18 PM', status: 'Contacted', avatar: 'NS' }, { name: 'Kabir Rao', property: 'Cedar Court', date: '08 Sep, 11:06 AM', status: 'Accepted', avatar: 'KR' }]; return <><PageTitle eyebrow={seller ? 'Seller workspace' : 'Your activity'} title={seller ? 'Interest requests' : 'Your requests'} copy={seller ? 'People who have raised their hand for your homes.' : 'A quiet record of the homes you’re considering.'}/><div className="request-stats"><Stat label={seller ? 'New requests' : 'Open requests'} value="04" note="+2 this week" icon={Bell}/><Stat label="In conversation" value="07" note="Across all listings" icon={Users}/><Stat label="Response rate" value="92%" note="You’re doing great" icon={Sparkles}/></div><div className="table-panel"><div className="table-head"><div><h2>{seller ? 'Recent interest' : 'Recent activity'}</h2><p>Updated moments ago</p></div><button className="secondary"><SlidersHorizontal size={16}/> Filter</button></div><div className="request-table">{requests.map(r => <div className="request-row" key={r.name}><span className="avatar">{r.avatar}</span><div><strong>{r.name}</strong><small>{r.property}</small></div><span className="request-date">{r.date}</span><span className={`status ${r.status.toLowerCase()}`}>{r.status}</span>{seller && <button className="row-action">Manage <ChevronDown size={15}/></button>}</div>)}</div></div></> }
function SellerDashboard() { return <><PageTitle eyebrow="Seller workspace" title="Your property portfolio" copy="A clear view of what’s moving and what needs your attention." action={<Link className="primary" to="/add-property"><Plus size={17}/> Add property</Link>}/><div className="request-stats"><Stat label="Active listings" value="08" note="2 added this month" icon={Building2}/><Stat label="Total views" value="1,284" note="+18.4% this week" icon={ArrowUpRight}/><Stat label="New interest" value="04" note="Needs your attention" icon={Bell}/></div><div className="section-heading listing-heading"><div><h2>Your listings</h2><p>Manage your live properties</p></div><Link to="/my-listings" className="text-link">View all <ArrowUpRight size={16}/></Link></div><div className="seller-list">{DEMO.slice(0, 3).map(p => <div className="seller-item" key={p.id}><img src={p.image}/><div className="seller-item-main"><span className="eyebrow">Active · Updated today</span><h3>{p.title}</h3><p><MapPin size={14}/> {p.location}</p></div><strong>{formatPrice(p.price)}</strong><Link className="icon-button" to={`/edit-property/${p.id}`}><Pencil size={17}/></Link><button className="icon-button muted"><Trash2 size={17}/></button></div>)}</div></> }
function PropertyForm({ edit }) { const navigate = useNavigate(); const [saved, setSaved] = useState(false); const submit = e => { e.preventDefault(); setSaved(true); setTimeout(() => navigate('/my-listings'), 500) }; return <><PageTitle eyebrow={edit ? 'Manage listing' : 'New listing'} title={edit ? 'Edit property' : 'Add a new property'} copy="Tell the story of a place someone will love."/><form className="property-form" onSubmit={submit}><div className="form-panel"><h2>Property details</h2><div className="form-grid"><label>Property title<input required placeholder="e.g. The Willow House"/></label><label>Location<input required placeholder="Neighbourhood, city"/></label><label>Property type<select><option>Apartment</option><option>Villa</option><option>House</option></select></label><label>Rooms<input type="number" min="1" defaultValue="3"/></label><label>Price<input required placeholder="₹ 1,25,00,000"/></label><label>Status<select><option>Active</option><option>Inactive</option></select></label><label className="span-2">Description<textarea rows="5" placeholder="What makes this home special?"/></label></div></div><div className="form-panel"><h2>Property images</h2><div className="upload-zone"><Plus size={22}/><strong>Drop images here or browse</strong><small>PNG, JPG up to 10MB each</small></div></div><div className="form-actions"><Link to="/my-listings" className="secondary">Cancel</Link><button className="primary" type="submit">{saved ? 'Saved ✓' : edit ? 'Save changes' : 'Publish listing'} <ArrowUpRight size={17}/></button></div></form></> }

createRoot(document.getElementById('root')).render(<App />)
